[project]
name = "transects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cmocean>=4.0.3",
    "matplotlib>=3.9.4",
    "netcdf4>=1.7.2",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
    "xarray>=2024.7.0",
]
